#!/bin/sh

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check for clang-format
if command_exists clang-format; then
    clang_format_available=true
else
    echo "Warning: clang-format is not available. Skipping C++ formatting."
    clang_format_available=false
fi

# Check for autopep8
if command_exists autopep8; then
    autopep8_available=true
else
    echo "Warning: autopep8 is not available. Skipping Python formatting."
    autopep8_available=false
fi

# Check for cmake-format
if command_exists cmake-format; then
    cmake_format_available=true
else
    echo "Warning: cmake-format is not available. Skipping CMake formatting."
    cmake_format_available=false
fi

# Run clang-format on staged C++ files
if [ "$clang_format_available" = true ]; then
    files_to_format=$(git diff --name-only --cached --diff-filter=ACMR | grep -E '\.(c|h|cpp|hpp)$')
    if [ -n "$files_to_format" ]; then
        echo "Formatting code with clang-format..."
        echo "$files_to_format" | xargs clang-format -i --style=file
        git add $files_to_format
        echo "Code formatted successfully."
    else
        echo "No relevant C++ files to format. Skipping clang-format."
    fi
fi

# Run autopep8 on staged Python and Godot files
if [ "$autopep8_available" = true ]; then
    files_to_format=$(git diff --name-only --cached --diff-filter=ACMR | grep -E '\.(py|gd)$')
    if [ -n "$files_to_format" ]; then
        echo "Formatting code with autopep8..."
        echo "$files_to_format" | xargs autopep8 --in-place --aggressive --aggressive  -q
        git add $files_to_format
        echo "Code formatted successfully."
    else
        echo "No relevant Python or Godot files to format. Skipping autopep8."
    fi
fi

# Run cmake-format on staged CMakeLists.txt files
if [ "$cmake_format_available" = true ]; then
    files_to_format=$(git diff --name-only --cached --diff-filter=ACMR | grep -E 'CMakeLists\.txt$')
    if [ -n "$files_to_format" ]; then
        echo "Formatting code with cmake-format..."
        echo "$files_to_format" | xargs cmake-format -i 
        git add $files_to_format
        echo "Code formatted successfully."
    else
        echo "No relevant CMake files to format. Skipping cmake-format."
    fi
fi

exit 0
