# set-option -g default-path "$PWD"

# New window in the same directory
bind c new-window -c "#{pane_current_path}"

# Split pane vertically in the same directory
bind '"' split-window -v -c "#{pane_current_path}"

# Split pane horizontally in the same directory
bind % split-window -h -c "#{pane_current_path}"

set -g status-left ' #S    '
#set -g status-left-length 40

# List of TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# tmux-resurrect options (optional but useful)
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# tmux-continuum options
# auto-save every 15 minutes
set -g @continuum-save-interval '15'
# auto-restore last session when tmux starts
set -g @continuum-restore 'on'

# Initialize TPM (keep this at the bottom)
run '~/.tmux/plugins/tpm/tpm'

