# set-option -g default-path "$PWD"

# New window in the same directory
bind c new-window -c "#{pane_current_path}"

# Split pane vertically in the same directory
bind '"' split-window -v -c "#{pane_current_path}"

# Split pane horizontally in the same directory
bind % split-window -h -c "#{pane_current_path}"

